CREATE TABLE relationship_event (
    event_id TEXT PRIMARY KEY,
    life_id TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    source_kind TEXT NOT NULL CHECK (source_kind <> ''),
    source_ref TEXT NOT NULL CHECK (source_ref <> ''),
    change_reason TEXT NOT NULL CHECK (change_reason <> ''),
    familiarity_delta INTEGER NOT NULL CHECK (familiarity_delta BETWEEN -1000 AND 1000),
    trust_delta INTEGER NOT NULL CHECK (trust_delta BETWEEN -1000 AND 1000),
    emotional_closeness_delta INTEGER NOT NULL CHECK (emotional_closeness_delta BETWEEN -1000 AND 1000),
    collaboration_delta INTEGER NOT NULL CHECK (collaboration_delta BETWEEN -1000 AND 1000),
    safety_delta INTEGER NOT NULL CHECK (safety_delta BETWEEN -1000 AND 1000),
    dependency_tendency_delta INTEGER NOT NULL CHECK (dependency_tendency_delta BETWEEN -1000 AND 1000),
    boundary_comfort_delta INTEGER NOT NULL CHECK (boundary_comfort_delta BETWEEN -1000 AND 1000),
    tension_delta INTEGER NOT NULL CHECK (tension_delta BETWEEN -1000 AND 1000),
    result_familiarity INTEGER NOT NULL CHECK (result_familiarity BETWEEN 0 AND 1000),
    result_trust INTEGER NOT NULL CHECK (result_trust BETWEEN -1000 AND 1000),
    result_emotional_closeness INTEGER NOT NULL CHECK (result_emotional_closeness BETWEEN 0 AND 1000),
    result_collaboration INTEGER NOT NULL CHECK (result_collaboration BETWEEN 0 AND 1000),
    result_safety INTEGER NOT NULL CHECK (result_safety BETWEEN -1000 AND 1000),
    result_dependency_tendency INTEGER NOT NULL CHECK (result_dependency_tendency BETWEEN 0 AND 1000),
    result_boundary_comfort INTEGER NOT NULL CHECK (result_boundary_comfort BETWEEN -1000 AND 1000),
    result_tension INTEGER NOT NULL CHECK (result_tension BETWEEN 0 AND 1000),
    applied_revision INTEGER NOT NULL CHECK (applied_revision > 0),
    event_time TEXT NOT NULL CHECK (event_time <> ''),
    policy_version INTEGER NOT NULL CHECK (policy_version > 0),
    created_at TEXT NOT NULL CHECK (created_at <> ''),
    FOREIGN KEY (life_id, subject_id) REFERENCES relationship_state(life_id, subject_id) ON DELETE CASCADE,
    UNIQUE (life_id, subject_id, source_kind, source_ref),
    UNIQUE (life_id, subject_id, applied_revision)
);
